main: com.hpfxd.pandaknockback.KnockbackPlugin
version: "${version}"
name: PandaKnockback
description: "${description}"
authors:
  - hpfxd
website: "https://github.com/hpfxd/PandaKnockback"

softdepend:
  - WorldGuard

commands:
  pandaknockback:
    usage: "/<command>"
    aliases:
      - knockback
      - kb
